services:
  - type: web
    name: channel-os
    env: static
    rootDir: channel-os
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: channel-os-app
    env: static
    rootDir: channel-os
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: channel-os-proxy
    env: node
    rootDir: channel-os
    buildCommand: echo "no build"
    startCommand: node proxy.js
    plan: free
